version: "3"

services:
  db:
    image: mysql
    container_name: data.db
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "greeder"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
    ports:
      - "3307:3307"
  web:
    build: ./
    container_name: data.server
    command: python manage.py runserver 0.0.0.0:8998
    volumes:
      - ./config:/srv/code
    ports:
      - "8998:8998"
    depends_on:
      - db
