# Generated by Django 3.2.7 on 2021-09-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('keyword', models.CharField(db_column='keyword', max_length=45)),
                ('desc', models.CharField(db_column='desc', max_length=255)),
                ('url', models.CharField(db_column='url', max_length=255)),
            ],
        ),
    ]
